# Generated by Django 2.2.2 on 2019-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190621_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
